apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: brainy-clownfish-python 
  janus-idp.io/tekton: brainy-clownfish-python
  backstage.io/kubernetes-id: brainy-clownfish-python
  backstage.io/kubernetes-namespace: rhtap-e2e-ci 
  app.kubernetes.io/part-of: brainy-clownfish-python
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  