apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: brainy-clownfish-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: brainy-clownfish-python 
  name: brainy-clownfish-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: brainy-clownfish-python 
