apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: brainy-clownfish-python-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/brainy-clownfish-python-gitops